### ISSUE TITLE
can't run it

### ISSUE THREAD

**Issue by GavinZhang00** [datbui/enhancer#4]
hello,
  if your project to run use train.sh? I can't run it successfully.

**Comment by datbui** [comment]
Hi championchampion,
Fixed! You can try again. Please, if everything is okay then close issue.

**Comment by GavinZhang00** [comment]
download function also has a error, adding follow code in 28 line of download.py can solve this problem.
if filename.find('?'):
        filename = filename[:filename.find('?')]

**Comment by datbui** [comment]
Actually, I don't get any errors...

try run from command line 

python download.py --dataset=lsun

or celebA, mnist
